### ISSUE TITLE
Fixed variable problem class category

### ISSUE THREAD

**Issue by qtothec** [gseastream/pyomo#1]
If I have a nonlinear model in which all of the binary variables are fixed, it should be recognized as NLP rather than MINLP by the writer.

**Comment by gseastream** [comment]
I changed the writer so that fixed variables are declared as free variables instead of maybe binary or integer, so now GAMS is able to recognize the model as LP or NLP if there are no unfixed MI variables. An additional step can be taken by the user if they include the holdfixed option (in the add_options keyword of the io_options argument to the solver/writer), which tells GAMS to treat fixed variables as constants to reduce the problem size.

**Comment by qtothec** [comment]
I don't know what @jsiirola will think of the fact that you change the variable domain declaration for fixed variables. Ordinarily, that would raise some concerns with me, but since the GAMS interface isn't designed to be user-readable anyways... idk.

**Comment by jsiirola** [comment]
Interesting. I would rather the Fixed variables not show up in the model at all.  I think that is doable, but will require some additional logic in the to_string logic.

**Comment by gseastream** [comment]
The following change labels fixed variables and expressions (if expressions show up in constraint bodies) with a string of their fixed values, so they do not show up as variables or expressions in the model at all and are treated exactly like constants:
```
def var_label(obj):
    if obj.is_fixed():
        return str(value(obj))
    return symbolMap.getSymbol(obj, var_recorder)
```
Is this the desired behavior?

**Comment by gseastream** [comment]
@qtothec I just realized something. Since this change now takes fixed variables out of the GAMS model completely (it replaces all occurrences of the variable with its value in the model file), GAMS no longer reports marginals for fixed variables. Is this ok?

Perhaps another thing of note is that since GAMS doesn't report a marginal for a fixed variable, the solver doesn't set a marginal for it either, and if a user tries to access a marginal that doesn't exist then pyomo throws a KeyError.

Just wondering if you were still expecting a marginal to show up for fixed variables.

**Comment by qtothec** [comment]
That is a fair question. My gut instinct is that the user would still expect to see a marginal for a fixed variable. Does GAMS report a marginal if you implement the fixing via var.FX?

**Comment by jsiirola** [comment]
FWIW, this behavior is consistent with the rest of Pyomo -- that is, fixed variables are never emitted to the solver, so no marginal is ever computed.

**Comment by qtothec** [comment]
Well, that works too.

**Comment by gseastream** [comment]
As a matter of fact GAMS does report marginals for variables fixed via the the var.fx method. But of course that would still require declaring and including the variable in the model, so if the pyomo standard is to leave it the way I made it, then I can do that.

**Comment by jsiirola** [comment]
My guess is that GAMS computes the marginals as a "service" to the user - and does not rely on the solver (or the solver's presolve) to calculate it for them.  I suspect that Pyomo could do the same...  BUT, I think that should be the responsibility of the general Pyomo solver API and not be baked into the GAMS solver interface.
